dependencies:
- name: jupyterhub
  version: 0.8.2
  repository: https://jupyterhub.github.io/helm-chart/
- name: airflow
  version: 4.1.1
  repository: https://charts.bitnami.com/bitnami
- name: sparkoperator
  version: 0.6.2
  repository: http://storage.googleapis.com/kubernetes-charts-incubator